CREATE TYPE USERROLE AS ENUM (
    'ADMIN',
    'OPERATOR',
    'CLIENT'
);

CREATE TABLE IF NOT EXISTS USERS (
    username VARCHAR(250) NOT NULL PRIMARY KEY,
    password VARCHAR(250) NOT NULL,
    role USERROLE NOT NULL
);